# A basic habitat configuration .yml file. We overwrite almost all these
# values in practice, see:
# projects/pointnav_baselines/experiments/habitat/debug_pointnav_habitat_base.py
# for an example of this.

ENVIRONMENT:
  MAX_EPISODE_STEPS: -1 # OVERWRITE WITH POS INT
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: -1 # OVERWRITE WITH POS INT
    HEIGHT: -1 # OVERWRITE WITH POS INT
  DEPTH_SENSOR:
    WIDTH: -1 # OVERWRITE WITH POS INT
    HEIGHT: -1 # OVERWRITE WITH POS INT
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: -1.0 # OVERWRITE WITH POS FLOAT

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: -1.0 # OVERWRITE WITH POS FLOAT EQUALLING SUCCESS_DISTANCE ABOVE
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: -1.0 # OVERWRITE WITH POS FLOAT EQUALLING SUCCESS_DISTANCE ABOVE

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: None
  POINTNAVV1:
    CONTENT_SCENES: []
