ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  TURN_ANGLE: 45
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.2
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 79
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
  SUCCESS_DISTANCE: 0.1

  SENSORS: ['OBJECTGOAL_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR']
  GOAL_SENSOR_UUID: objectgoal

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.1
  SPL:
    TYPE: SPL
    DISTANCE_TO: VIEW_POINTS
    SUCCESS_DISTANCE: 0.1
  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS

DATASET:
  TYPE: ObjectNav-v1
  SPLIT: train
  DATA_PATH: "data/datasets/objectnav/mp3d/v0/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/"
